# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class StatusServiceStub(object):
    """get the number of connected clients
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConnectedClients = channel.unary_unary(
                '/main.StatusService/GetConnectedClients',
                request_serializer=messages__pb2.Empty.SerializeToString,
                response_deserializer=messages__pb2.Status.FromString,
                )


class StatusServiceServicer(object):
    """get the number of connected clients
    """

    def GetConnectedClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConnectedClients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedClients,
                    request_deserializer=messages__pb2.Empty.FromString,
                    response_serializer=messages__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.StatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatusService(object):
    """get the number of connected clients
    """

    @staticmethod
    def GetConnectedClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.StatusService/GetConnectedClients',
            messages__pb2.Empty.SerializeToString,
            messages__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
