# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x04main\"\x07\n\x05\x45mpty\"\"\n\x06Status\x12\x18\n\x10\x63onnectedClients\x18\x01 \x01(\x05\x32\x43\n\rStatusService\x12\x32\n\x13GetConnectedClients\x12\x0b.main.Empty\x1a\x0c.main.Status\"\x00\x42(Z&github.com/lobis/baldosas-server/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/lobis/baldosas-server/proto'
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_STATUS']._serialized_start=33
  _globals['_STATUS']._serialized_end=67
  _globals['_STATUSSERVICE']._serialized_start=69
  _globals['_STATUSSERVICE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
